### ISSUE TITLE
did not match C++ signature

### ISSUE THREAD

**Issue by Fhrozen** [drasmuss/hessianfree#7]
hi, i wondering about the gpu program.
I know that is still a WIP but i am not sure if you know about these problems:
First:
using the test_demo
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================= 1 failed in 2.39 seconds =========================================================
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered

So probably could be a memory allocation. I did not check where the problem is.

Also trying to run the program but with my own data i got this
Boost.Python.ArgumentError: Python argument types in
    Function._set_block_shape(Function, numpy.int32, numpy.int32, int)
did not match C++ signature:
    _set_block_shape(pycuda::function {lvalue}, int, int, int)
and when i modify the code trying to match ints i got this:
 No registered converter was able to produce a C++ rvalue of type unsigned int from this Python object of type numpy.int32

so i am not sure what is wrong.

I did not try to check for more specific errors because i dont have much time. 
Also, I was trying to modify the code moving all of the operations to the gpu since the longest the train goes, the slowest it becomes. But I do not have much time to check. However i was trying with the scikit-cuda lib that includes the cublas operations.

As soon as ill get free i will try to move the code to cublas.. 
Thanks

**Comment by drasmuss** [comment]
I've actually been working on redoing the GPU code, moving the whole curvature calculation onto the GPU.  It's not in a working state yet, but should be finished within the week (you can check it out in the `gpu_g` branch if you're interested).  That being said, I don't see those problems you're seeing on my machine, so it must be some kind of version problem.  So hopefully the new GPU code will just work for you, but if not we can try to track down the problem there.

**Comment by drasmuss** [comment]
The GPU changes are merged into master now, so you can take a look and see if you're still getting the same error.

**Comment by Fhrozen** [comment]
Yep, it looks like when i try to make the test with mnist gpu on ubuntu still doe not works. I am not sure if is a library problem because i am using:
Boost 1.59
Pycuda 2015.1.3
numpy 1.10.1

the problem is that i dont know if there is and additional wrapping library in ubuntu, because i also test it in windows and the pytest doesnt give me any error.

So i will check where is the problem.

**Comment by drasmuss** [comment]
I pushed some changes to the `gpu_compat` branch, could you see if those fix the problem for you?

**Comment by Fhrozen** [comment]
The gpu_compat looks to solve the problem. 
Tested with test_demos and test_gpu and works well.
I will try with a different dataset, but it looks like now is working . 

Thanks

**Comment by drasmuss** [comment]
Great, thanks!  I'll merge that in to master.
